packages:
  - packages/*
  - playgrounds/*
  - docs
catalog:
  '@commitlint/cli': ^19.6.1
  '@commitlint/config-conventional': ^19.6.0
  '@egoist/tailwindcss-icons': ^1.8.2
  '@iconify-json/ri': ^1.2.4
  '@microlink/react-json-view': ^1.23.4
  '@next/env': ^15.1.0
  '@radix-ui/react-accordion': ^1.2.2
  '@radix-ui/react-checkbox': ^1.1.3
  '@radix-ui/react-collapsible': ^1.1.2
  '@radix-ui/react-dialog': ^1.1.4
  '@radix-ui/react-dropdown-menu': ^2.1.4
  '@radix-ui/react-label': ^2.1.1
  '@radix-ui/react-popover': ^1.1.4
  '@radix-ui/react-radio-group': ^1.2.2
  '@radix-ui/react-scroll-area': ^1.2.2
  '@radix-ui/react-select': ^2.1.4
  '@radix-ui/react-separator': ^1.1.1
  '@radix-ui/react-slot': ^1.1.1
  '@radix-ui/react-tabs': ^1.1.2
  '@radix-ui/react-toast': ^1.2.4
  '@radix-ui/react-toggle': ^1.1.1
  '@radix-ui/react-toggle-group': ^1.1.1
  '@radix-ui/react-tooltip': ^1.1.6
  '@release-it/bumper': ^6.0.1
  '@release-it/conventional-changelog': ^9.0.3
  '@tanstack/react-query': ^5.62.7
  '@tanstack/react-table': ^8.20.6
  '@tanstack/react-virtual': ^3.11.2
  '@types/fs-extra': ^11.0.4
  '@types/mime-types': ^2.1.4
  '@types/node': ^22.10.2
  '@types/semver': ^7.5.8
  '@types/ws': ^8.5.13
  '@vitejs/plugin-react': ^4.3.4
  '@xystack/style-guide': ^0.2.5
  address: ^2.0.3
  autoprefixer: ^10.4.20
  babel-plugin-react-compiler: 19.0.0-beta-201e55d-20241215
  birpc: ^0.2.19
  bunchee: ^6.0.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.0.4
  cobe: ^0.6.3
  commitizen: ^4.3.1
  consola: ^3.2.3
  copyfiles: ^2.4.1
  cross-env: ^7.0.3
  cz-conventional-changelog: ^3.3.0
  date-fns: ^4.1.0
  dotenv: ^16.4.7
  es-toolkit: ^1.30.1
  eslint: ^9.17.0
  execa: ^9.5.2
  fast-glob: ^3.3.2
  fast-npm-meta: ^0.2.2
  fkill: ^9.0.0
  fs-extra: ^11.2.0
  get-port-please: ^3.1.2
  immer: ^10.1.1
  is-installed-globally: ^1.0.0
  lint-staged: ^15.2.11
  microdiff: ^1.4.0
  mime-types: ^2.1.35
  motion: 12.0.0-alpha.2
  next-themes: ^0.4.4
  npm-run-all: ^4.1.5
  nypm: ^0.4.1
  postcss: ^8.4.49
  posthog-js: ^1.203.1
  prettier: ^3.4.2
  pretty-ms: ^9.2.0
  react-docgen: ^7.1.0
  react-resizable-panels: ^2.1.7
  react-router: ^7.0.2
  react-use: ^17.6.0
  release-it: ^17.10.0
  schema-dts: ^1.1.2
  semver: ^7.6.3
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.0
  sonner: ^1.7.1
  sugar-high: ^0.7.5
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.16
  tailwindcss-animate: ^1.0.7
  taze: ^0.18.0
  turbo: ^2.3.3
  typescript: ^5.7.2
  vite: ^6.0.3
  webpack: ^5.97.1
  webpack-bundle-analyzer: ^4.10.2
  ws: ^8.18.0
  xterm: 5.2.1
  xterm-addon-fit: ^0.8.0
  zod: ^3.24.1
  zustand: ^5.0.2
catalogs:
  next14:
    next: 14.2.18
  next15:
    next: 15.1.1
  react18:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    react: 19.0.0
    react-dom: 19.0.0
