packages:
  - packages/*
  - playgrounds/*
  - docs
catalog:
  '@egoist/tailwindcss-icons': ^1.8.1
  '@iconify-json/ri': ^1.2.3
  '@tanstack/react-query': ^5.62.2
  '@tanstack/react-table': ^8.20.5
  '@tanstack/react-virtual': ^3.11.0
  '@types/node': ^22.10.1
  '@xystack/style-guide': ^0.2.5
  autoprefixer: ^10.4.20
  birpc: ^0.2.19
  clsx: ^2.1.1
  consola: ^3.2.3
  date-fns: ^4.1.0
  eslint: ^9.16.0
  framer-motion: ^11.13.1
  postcss: ^8.4.49
  prettier: ^3.4.2
  superjson: ^2.2.2
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.16
  typescript: ^5.7.2
  webpack: ^5.97.1
  zod: ^3.23.8
  zustand: ^5.0.2
catalogs:
  react18:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    react: 19.0.0
    react-dom: 19.0.0
  next14:
    next: 14.2.18
  next15:
    next: 15.0.4
