packages:
  - packages/*
  - playgrounds/*
  - docs
catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@egoist/tailwindcss-icons': ^1.9.0
  '@iconify-json/ri': ^1.2.5
  '@microlink/react-json-view': ^1.26.2
  '@next/env': ^15.3.3
  '@radix-ui/react-accordion': ^1.2.11
  '@radix-ui/react-checkbox': ^1.3.2
  '@radix-ui/react-collapsible': ^1.1.11
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-popover': ^1.1.14
  '@radix-ui/react-radio-group': ^1.3.7
  '@radix-ui/react-scroll-area': ^1.2.9
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-toast': ^1.2.14
  '@radix-ui/react-toggle': ^1.1.9
  '@radix-ui/react-toggle-group': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.7
  '@release-it/bumper': ^7.0.5
  '@release-it/conventional-changelog': ^10.0.1
  '@tanstack/react-query': ^5.80.7
  '@tanstack/react-table': ^8.21.3
  '@tanstack/react-virtual': ^3.13.10
  '@types/fs-extra': ^11.0.4
  '@types/mime-types': ^3.0.1
  '@types/node': ^24.0.3
  '@types/semver': ^7.7.0
  '@types/ws': ^8.18.1
  '@tailwindcss/postcss': ^4.1.10
  '@tailwindcss/vite': ^4.1.10
  '@vitejs/plugin-react': ^4.5.2
  '@xyflow/react': ^12.7.0
  '@xystack/style-guide': ^0.3.11
  address: ^2.0.3
  autoprefixer: ^10.4.21
  babel-plugin-react-compiler: 19.0.0-beta-201e55d-20241215
  birpc: ^2.4.0
  bunchee: ^6.5.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  cobe: ^0.6.4
  commitizen: ^4.3.1
  consola: ^3.4.2
  copyfiles: ^2.4.1
  cross-env: ^7.0.3
  cz-conventional-changelog: ^3.3.0
  date-fns: ^4.1.0
  dotenv: ^16.5.0
  es-toolkit: ^1.39.3
  eslint: ^9.29.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  fast-npm-meta: ^0.4.3
  fkill: ^9.0.0
  fs-extra: ^11.3.0
  get-port-please: ^3.1.2
  immer: ^10.1.1
  is-installed-globally: ^1.0.0
  lint-staged: ^16.1.2
  microdiff: ^1.5.0
  mime-types: ^3.0.1
  motion: 12.0.0-alpha.2
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  nypm: ^0.6.0
  postcss: ^8.5.6
  posthog-js: ^1.254.0
  prettier: ^3.5.3
  pretty-ms: ^9.2.0
  react-docgen: ^8.0.0
  react-resizable-panels: ^3.0.3
  react-router: ^7.6.2
  react-use: ^17.6.0
  release-it: ^19.0.3
  schema-dts: ^1.1.5
  semver: ^7.7.2
  simple-git-hooks: ^2.13.0
  sirv: ^3.0.1
  sonner: ^2.0.5
  sugar-high: ^0.9.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  tailwindcss-animate: ^1.0.7
  taze: ^19.1.0
  turbo: ^2.5.4
  typescript: ^5.8.3
  vite: ^6.3.5
  webpack: ^5.99.9
  webpack-bundle-analyzer: ^4.10.2
  ws: ^8.18.2
  xterm: 5.2.1
  xterm-addon-fit: ^0.8.0
  zod: ^3.25.67
  zustand: ^5.0.5
catalogs:
  next14:
    next: 14.2.18
  next15:
    next: 15.1.1
  react18:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    react: 19.0.0
    react-dom: 19.0.0
