packages:
  - packages/*
  - playgrounds/*
  - docs
catalog:
  '@egoist/tailwindcss-icons': ^1.8.1
  '@iconify-json/ri': ^1.2.3
  '@tanstack/react-query': ^5.61.3
  '@trpc/client': 11.0.0-rc.643
  '@trpc/react-query': 11.0.0-rc.643
  '@trpc/server': 11.0.0-rc.643
  '@types/node': ^22.10.0
  '@xystack/style-guide': ^0.2.5
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  consola: ^3.2.3
  eslint: ^9.15.0
  framer-motion: ^11.11.17
  postcss: ^8.4.49
  prettier: ^3.4.0
  superjson: ^2.2.1
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.15
  typescript: ^5.7.2
  zod: ^3.23.8
  zustand: ^5.0.1
catalogs:
  react18:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: ^18.3.1
    react-dom: ^18.3.1
  react19:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106
  next14:
    next: ^14.2.18
  next15:
    next: ^15.0.3
