packages:
  - packages/*
  - playgrounds/*
  - docs
catalog:
  '@egoist/tailwindcss-icons': ^1.8.1
  '@iconify-json/ri': ^1.2.3
  '@types/node': ^20.17.7
  '@xystack/style-guide': ^0.2.4
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  eslint: ^9.15.0
  framer-motion: ^11.11.17
  postcss: ^8.4.49
  prettier: ^3.3.3
  tailwind-merge: ^2.5.4
  tailwindcss: ^3.4.15
  typescript: ^5.7.2
catalogs:
  react:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: ^18
    react-dom: ^18
  react19:
    '@types/react': ^18
    '@types/react-dom': ^18
    react: 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106
  next14:
    next: ^14.2.18
  next15:
    next: ^15.0.3
