packages:
  - packages/*
  - playgrounds/*
  - docs
catalog:
  '@commitlint/cli': ^19.6.0
  '@commitlint/config-conventional': ^19.6.0
  '@egoist/tailwindcss-icons': ^1.8.1
  '@iconify-json/ri': ^1.2.3
  '@microlink/react-json-view': ^1.23.4
  '@next/env': ^15.0.4
  '@radix-ui/react-accordion': ^1.2.1
  '@radix-ui/react-checkbox': ^1.1.2
  '@radix-ui/react-dialog': ^1.1.2
  '@radix-ui/react-dropdown-menu': ^2.1.2
  '@radix-ui/react-label': ^2.1.0
  '@radix-ui/react-popover': ^1.1.2
  '@radix-ui/react-radio-group': ^1.2.1
  '@radix-ui/react-scroll-area': ^1.2.1
  '@radix-ui/react-select': ^2.1.2
  '@radix-ui/react-separator': ^1.1.0
  '@radix-ui/react-slot': ^1.1.0
  '@radix-ui/react-tabs': ^1.1.1
  '@radix-ui/react-toast': ^1.2.2
  '@radix-ui/react-toggle': ^1.1.0
  '@radix-ui/react-toggle-group': ^1.1.0
  '@radix-ui/react-tooltip': ^1.1.4
  '@release-it/bumper': ^6.0.1
  '@release-it/conventional-changelog': ^9.0.3
  '@tanstack/react-query': ^5.62.3
  '@tanstack/react-table': ^8.20.5
  '@tanstack/react-virtual': ^3.11.0
  '@types/fs-extra': ^11.0.4
  '@types/mime-types': ^2.1.4
  '@types/node': ^22.10.1
  '@types/semver': ^7.5.8
  '@types/ws': ^8.5.13
  '@vitejs/plugin-react-swc': ^3.7.2
  '@xystack/style-guide': ^0.2.5
  'address': ^2.0.3
  'autoprefixer': ^10.4.20
  'birpc': ^0.2.19
  'bunchee': ^6.0.2
  'class-variance-authority': ^0.7.1
  'clsx': ^2.1.1
  'cmdk': ^1.0.4
  'cobe': ^0.6.3
  'commitizen': ^4.3.1
  'consola': ^3.2.3
  'copyfiles': ^2.4.1
  'cross-env': ^7.0.3
  'cz-conventional-changelog': ^3.3.0
  'date-fns': ^4.1.0
  'dotenv': ^16.4.7
  'eslint': ^9.16.0
  'execa': ^9.5.1
  'fast-glob': ^3.3.2
  'fast-npm-meta': ^0.2.2
  'fkill': ^9.0.0
  'framer-motion': ^11.13.1
  'fs-extra': ^11.2.0
  'get-port-please': ^3.1.2
  'husky': ^9.1.7
  'immer': ^10.1.1
  'is-installed-globally': ^1.0.0
  'lint-staged': ^15.2.10
  'microdiff': ^1.4.0
  'mime-types': ^2.1.35
  'next-themes': ^0.4.4
  'npm-run-all': ^4.1.5
  'nypm': ^0.4.1
  'postcss': ^8.4.49
  'prettier': ^3.4.2
  'pretty-ms': ^9.2.0
  'react-dev-inspector': ^2.0.1
  'react-docgen': ^7.1.0
  'react-resizable-panels': ^2.1.7
  'react-router': ^7.0.2
  'react-use': ^17.5.1
  'release-it': ^17.10.0
  'semver': ^7.6.3
  'sirv': ^3.0.0
  'sonner': ^1.7.0
  'sugar-high': ^0.7.5
  'superjson': ^2.2.2
  'tailwind-merge': ^2.5.5
  'tailwindcss': ^3.4.16
  'tailwindcss-animate': ^1.0.7
  'taze': ^0.18.0
  'turbo': ^2.3.3
  'typescript': ^5.7.2
  'vite': ^6.0.3
  'webpack': ^5.97.1
  'webpack-bundle-analyzer': ^4.10.2
  'ws': ^8.18.0
  'xterm': 5.2.1
  'xterm-addon-fit': ^0.8.0
  'zod': ^3.23.8
  'zustand': ^5.0.2
catalogs:
  next14:
    'next': 14.2.18
  next15:
    'next': 15.0.4
  react18:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    'react': 18.3.1
    'react-dom': 18.3.1
  react19:
    '@types/react': 18.3.14
    '@types/react-dom': 18.3.2
    'react': 19.0.0
    'react-dom': 19.0.0
