import './globals.css'
import { Inter } from 'next/font/google'
import { NextDevtoolsProvider } from '@next-devtools/core'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextDevtoolsProvider>
          {children}
        </NextDevtoolsProvider>
      </body>
    </html>
  )
}
